using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Models
{
    /// <summary>
    /// Represents a marketing campaign.
    /// </summary>
    public class Campaign
    {
        /// <summary>
        /// Gets or sets the primary key for the campaign.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CampaignId { get; set; }

        /// <summary>
        /// Gets or sets the name of the campaign.
        /// </summary>
        [Required]
        [StringLength(100)]
        public string CampaignName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the type of the campaign (e.g., Acquisition, Retention).
        /// </summary>
        [Required]
        [StringLength(50)]
        public string CampaignType { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the marketing channel (e.g., Email, SMS, Social Media).
        /// </summary>
        [Required]
        [StringLength(50)]
        public string MarketingChannel { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the total budget allocated to the campaign.
        /// </summary>
        [Range(0, 100000000)]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Budget { get; set; }

        /// <summary>
        /// Gets or sets the actual spend on the campaign.
        /// </summary>
        [Range(0, 100000000)]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Spend { get; set; }

        /// <summary>
        /// Gets or sets the revenue generated by the campaign.
        /// </summary>
        [Range(0, 1000000000)]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Revenue { get; set; }

        /// <summary>
        /// Gets or sets the number of conversions.
        /// </summary>
        [Range(0, int.MaxValue)]
        public int Conversions { get; set; }

        /// <summary>
        /// Gets or sets the number of clicks.
        /// </summary>
        [Range(0, int.MaxValue)]
        public int Clicks { get; set; }

        /// <summary>
        /// Gets or sets the number of impressions.
        /// </summary>
        [Range(0, int.MaxValue)]
        public int Impressions { get; set; }

        /// <summary>
        /// Gets or sets the start date of the campaign.
        /// </summary>
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets the end date of the campaign.
        /// </summary>
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Gets or sets the status of the campaign (e.g., Active, Completed, Paused).
        /// </summary>
        [Required]
        [StringLength(20)]
        public string Status { get; set; } = "Active";

        /// <summary>
        /// Gets or sets the date and time when the record was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Navigation property for campaign responses.
        /// </summary>
        public ICollection<CampaignResponse> CampaignResponses { get; set; } = new List<CampaignResponse>();
    }
}
